name: Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    services:
      flask:
        image: python:3.9
        ports:
          - 5001:5001
        options: --health-cmd "curl http://localhost:5001" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r flask-app/requirments.txt
    
    - name: Install Node.js dependencies
      run: |
        npm install
    
    - name: Start Flask Application
      run: |
        cd flask-app
        python task.py &
        sleep 5  # Wait for the application to start
      
    - name: Run Artillery Tests
      run: |
        npm run test:report
      
    - name: Upload Performance Results
      uses: actions/upload-artifact@v2
      with:
        name: performance-results
        path: |
          report.json
          report.html
